Settings.defaults[:blog_title] = 'Blog'
Settings.defaults[:about_title] = 'About'
Settings.defaults[:contact_title] = 'Contact'
Settings.defaults[:show_blog] = 'false'
Settings.defaults[:show_about] = 'false'
Settings.defaults[:show_contact] = 'false'