Settings.defaults[:news_title] = 'Blog'
Settings.defaults[:bio_title] = 'About'
Settings.defaults[:contact_title] = 'Contact'
Settings.defaults[:show_news] = 'true'
Settings.defaults[:show_bio] = 'true'
Settings.defaults[:show_contact] = 'true'