development:
  bucket: [YOUR BUCKET NAME HERE]
  access_key_id: [YOUR ACCESS KEY HERE]
  secret_access_key: [YOUR SECRED KEY HERE]

test:
  bucket: [YOUR BUCKET NAME HERE]
  access_key_id: [YOUR ACCESS KEY HERE]
  secret_access_key: [YOUR SECRED KEY HERE]

production:
  bucket: [YOUR BUCKET NAME HERE]
  access_key_id: [YOUR ACCESS KEY HERE]
  secret_access_key: [YOUR SECRED KEY HERE]