development:
  bucket: trmw-testing
  access_key_id: AKIAJXHX55SJ566WFBKA
  secret_access_key: 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

test:
  bucket: trmw-testing
  access_key_id: AKIAJXHX55SJ566WFBKA
  secret_access_key: 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

production:
  bucket: dru
  access_key_id: AKIAJXHX55SJ566WFBKA
  secret_access_key: 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