# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen

content_css: /stylesheets/application.css
theme: advanced
theme_advanced_buttons1: bold,italic,|,link,unlink,|,undo,redo,|,code
theme_advanced_buttons2: ""
theme_advanced_buttons3: ""
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
valid_elements: a[href|target=_blank],strong/b,em/i,p,br
plugins: [ inlinepopups ]